[2024-05-05 13:09:45,973] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_prostgres_hooks.poastgres_to_s3 2024-05-05T13:07:43.591069+00:00 [queued]>
[2024-05-05 13:09:45,996] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_prostgres_hooks.poastgres_to_s3 2024-05-05T13:07:43.591069+00:00 [queued]>
[2024-05-05 13:09:45,997] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-05 13:09:45,998] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2024-05-05 13:09:45,998] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-05 13:09:46,009] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): poastgres_to_s3> on 2024-05-05T13:07:43.591069+00:00
[2024-05-05 13:09:46,013] {standard_task_runner.py:52} INFO - Started process 5182 to run task
[2024-05-05 13:09:46,018] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_prostgres_hooks', 'poastgres_to_s3', '2024-05-05T13:07:43.591069+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp50pikgzh', '--error-file', '/tmp/tmph8syjrti']
[2024-05-05 13:09:46,021] {standard_task_runner.py:77} INFO - Job 28: Subtask poastgres_to_s3
[2024-05-05 13:09:46,074] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_prostgres_hooks.poastgres_to_s3 2024-05-05T13:07:43.591069+00:00 [running]> on host d4a0c764ecae
[2024-05-05 13:09:46,125] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mark
AIRFLOW_CTX_DAG_ID=dag_with_prostgres_hooks
AIRFLOW_CTX_TASK_ID=poastgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-05-05T13:07:43.591069+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-05T13:07:43.591069+00:00
[2024-05-05 13:09:46,138] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2024-05-05 13:09:46,165] {dag_with_postgres_hooks.py:32} INFO - Saved orders data in text file: dags/get_orders_20240505.txt
[2024-05-05 13:09:46,166] {taskinstance.py:1455} ERROR - missing a required argument: 'filename'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 39, in postgres_to_S3
    replace=True
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 52, in wrapper
    bound_args = function_signature.bind(*args, **kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/local/lib/python3.6/inspect.py", line 2912, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'filename'
[2024-05-05 13:09:46,172] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_prostgres_hooks, task_id=poastgres_to_s3, execution_date=20240505T130743, start_date=20240505T130945, end_date=20240505T130946
[2024-05-05 13:09:46,231] {local_task_job.py:146} INFO - Task exited with return code 1
